### 1. VECTORS, MATRICES & ARRAYS

In [1]:
import numpy as np
from scipy import sparse

In [5]:
matrix = ([[0,0],
          [0,1],
          [3,0]])

matrix

[[0, 0], [0, 1], [3, 0]]

In [6]:
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [27]:
new_matrix = ([[3, 4, 6],
              [7, 6, 8],
              [3, 1, 7],
              [6, 9, 4]])
#new_matrix.mean()
np.std(new_matrix, axis=0)
new_array = np.array(new_matrix)
new_array

array([[3, 4, 6],
       [7, 6, 8],
       [3, 1, 7],
       [6, 9, 4]])

In [31]:
my_array = new_array.reshape(3,4)
my_array

array([[3, 4, 6, 7],
       [6, 8, 3, 1],
       [7, 6, 9, 4]])

In [32]:
my_array.T

array([[3, 6, 7],
       [4, 8, 6],
       [6, 3, 9],
       [7, 1, 4]])