### 1. VECTORS, MATRICES & ARRAYS

In [1]:
import numpy as np
from scipy import sparse

In [2]:
matrix = ([[0,0],
          [0,1],
          [3,0]])

matrix

[[0, 0], [0, 1], [3, 0]]

In [3]:
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [4]:
new_matrix = ([[3, 4, 6],
              [7, 6, 8],
              [3, 1, 7],
              [6, 9, 4]])
#new_matrix.mean()
np.std(new_matrix, axis=0)
new_array = np.array(new_matrix)
new_array

array([[3, 4, 6],
       [7, 6, 8],
       [3, 1, 7],
       [6, 9, 4]])

In [5]:
my_array = new_array.reshape(3,4)
my_array

array([[3, 4, 6, 7],
       [6, 8, 3, 1],
       [7, 6, 9, 4]])

In [18]:
transposed_array = my_array.T
transposed_array

array([[3, 6, 7],
       [4, 8, 6],
       [6, 3, 9],
       [7, 1, 4]])

In [7]:
print(transposed_array[1, 1])

print('\n',transposed_array[:3,2])

print('\n',transposed_array[3, :])

print('\n',transposed_array[1:3, 1:])

print('\n',transposed_array[2:, 1:2])

8

 [7 6 9]

 [7 1 4]

 [[8 6]
 [3 9]]

 [[3]
 [1]]


In [8]:
print('\n',transposed_array.shape)
print('\n',transposed_array.size)
print('\n',transposed_array.dtype)
print('\n',transposed_array.ndim)


 (4, 3)

 12

 int64

 2


In [9]:
print('\n',transposed_array.max(axis=0))
print('\n',transposed_array.min())


 [7 8 9]

 1


##### Flattening
- Transoform a matrix into a one dimensional array


In [10]:
flat_martix = transposed_array.flatten()
flat_martix

array([3, 6, 7, 4, 8, 6, 6, 3, 9, 7, 1, 4])

##### Rank of a matrix
- The rank of a matrix is the dimensions of the vector space spanned by its columns or rows.
Finding the rank of a matrix is easy in NumPy thanks to matrix_rank.

In [11]:
np.linalg.matrix_rank(transposed_array)

3

#### Diagonal of a matrix

In [12]:
transposed_array.diagonal()

array([3, 8, 9])

#### Trace of a matrix
- The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods.

In [13]:
print(transposed_array.trace())
print(sum(transposed_array.diagonal()))

20
20


In [14]:
np.dot(transposed_array, my_array)

array([[ 94, 102,  99,  55],
       [102, 116, 102,  60],
       [ 99, 102, 126,  81],
       [ 55,  60,  81,  66]])



#### Inverse of a matrix
- The inverse of a square matrix, A, is a second matrix, A–1, such that:

AA ^−1 = I

- where I is the identity matrix. In NumPy we can use linalg.inv to calculate A–1 if it exists.

- Non-square matrices do not have inverses.

In [22]:
sq_matrix = transposed_array[:3, :3]

inverse_matrix = np.linalg.inv(sq_matrix)
inverse_matrix

array([[-6.00000000e-01,  3.66666667e-01,  2.22222222e-01],
       [-2.22044605e-17,  1.66666667e-01, -1.11111111e-01],
       [ 4.00000000e-01, -3.00000000e-01, -1.11022302e-17]])