### 2. LOADING DATA

In [1]:
import numpy as np
from sklearn import datasets
import pandas as pd

In [6]:
digits = datasets.load_digits()

features = digits.data

targets = digits.target

features[2]

array([ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
       14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
        1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
        0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  3., 13., 16.,
       16., 11.,  5.,  0.,  0.,  0.,  0.,  3., 11., 16.,  9.,  0.])

In [7]:
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

#### Creating a Simulated Dataset
- scikit-learn offers many methods for creating simulated data. Of those, three methods are particularly useful:
    - make_regression - creating simulated dataset for regression
    - make_classification - simulated dataset for classification
    - make_blobs - dataset designed to work with clustering techniques

In [13]:
from sklearn.datasets import make_regression, make_classification


features, target, coefficients = make_regression(n_samples=100,
                                                n_features=3,
                                                n_informative=3,
                                                n_targets=1,
                                                noise=0.0,
                                                coef=True,
                                                random_state=1
                                                )
# View feature matrix and target vector
print('Feature Matrix \n', features[:3])
print('\nTarget Vector\n', target[:3])

coefficients

Feature Matrix 
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]

Target Vector
 [-10.37865986  25.5124503   19.67705609]


array([44.19042807, 98.97517077, 58.15774073])

In [19]:
features, target = make_classification(
    n_samples=100,
    n_features=3,
    n_informative=3,
    n_redundant=0,
    n_classes=2,
    weights=[.25, .75],
    random_state=1
)

# View feature matrix and target vector
print('Feature Matrix\n', features[:3])
print('Target Vector\n', target[:3])

Feature Matrix
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]
Target Vector
 [1 0 0]


In [20]:
#### Reading Remote SQL Database